use std::path::Path;

use crate::emit::markers::{inject_section, wrap_with_markers};
use crate::model::Brief;


/// Emit a human-readable readme from a Brief.
///
/// This function is designed to emit a human-readable readme from a .brief.md file.
/// README.md is the typical, human-readable file that provides an overview of a project and its purpose.
/// It is designed to be human-readable, concise, and informative, so it is a natural match for
pub fn emit_readme(brief: &Brief) -> String {
    let mut out = String::new();

    out.push_str("# Readme -*- mode: markdown -*-\n\n");
    out.push_str("## NOTE: this file is auto-generated from the .brief.md file.\n## Do not edit this file manually\n\n");
    out.push_str(&format!("Project Goal: {}\n\n", brief.goal));


    // Technology Stack
    if !brief.frontmatter.stack.is_empty() {
        out.push_str(&format!(
            "Project Technology Stack: {}\n\n",
            brief.frontmatter.stack.join(", ")
        ));
    }
    // Context
    if !brief.frontmatter.context.is_empty() {
        out.push_str("See Also:\n\n");
        for ctx in &brief.frontmatter.context {
            out.push_str(&format!("- `{ctx}`\n"));
        }
        out.push('\n');
    }

    out
}

/// Inject a briefing section into an existing README.md or create one.
///
/// Behaves identically to `install_claude` for CLAUDE.md: wraps the emitted
/// section in `<brief:generated>` markers, replaces the first existing pair
/// in place (migrating the legacy `<!-- brief:start -->` flavor), strips
/// empty extra pairs, and appends if no markers exist. Codex CLI consumes
/// AGENTS.md without sanitizing the wrapped markers, so the encapsulation
/// round-trip works the same way.
pub fn install_readme(brief: &Brief, readme_path: &Path) -> Result<String, std::io::Error> {
    let section = emit_readme(brief);
    let wrapped = wrap_with_markers(&section);

    let output = if readme_path.exists() {
        let existing = std::fs::read_to_string(readme_path)?;
        let (result, pairs_found) = inject_section(&existing, &wrapped);
        if pairs_found > 1 {
            eprintln!(
                "warning: found {} brief marker pairs; using the first, stripping remaining empty pairs",
                pairs_found
            );
        }
        result
    } else {
        wrapped
    };

    std::fs::write(readme_path, &output)?;
    Ok(output)
}

#[cfg(test)]
mod tests {
    use crate::emit::{emit_agents_md, install_agents_md};
    use super::*;
    use crate::model::*;

    #[test]
    fn readme_marks_hard_as_required() {
        let brief = Brief {
            frontmatter: Frontmatter::default(),
            goal: "Build feature".into(),
            identity: None,
            constraints: Constraints {
                hard: vec!["Must pass CI".into()],
                soft: vec![],
                ask_first: vec![]
            },
            sacred: vec![],
            assumptions: vec![],
            deliverable: None,
            unknown_sections: vec![]
        };
        let output = emit_readme(&brief);
        assert!(output.contains("Must pass CI **(REQUIRED)**"));
    }

    #[test]
    fn readme_emits_unknown_sections() {
        let brief = Brief {
            frontmatter: Frontmatter::default(),
            goal: "This super project Goal".into(),
            identity: None,
            constraints: Constraints::default(),
            sacred: vec![],
            assumptions: vec![],
            deliverable: None,
            unknown_sections: vec![UnknownSection {
                heading: "Commands".into(),
                content: "- Build: `cargo build`".into(),
            }],
        };
        let output = emit_readme(&brief);
        assert!(output.contains("## Commands"));
        assert!(output.contains("- Build: `cargo build`"))
    }

    #[test]
    fn readme_uses_protected_files_heading() {
        let brief = Brief {
            frontmatter: Frontmatter::default(),
            goal: "Awesomely Project Goal".into(),
            identity: None,
            constraints: Constraints::default(),
            sacred: vec![SacredEntry {
                path: "src/auth/**".into(),
                reason: "Auth".into(),
                well_formed: true,
            }],
            assumptions: vec![],
            deliverable: None,
            unknown_sections: vec![],
        };
        let output = emit_agents_md(&brief);
        assert!(output.contains("## Protected Files"));
        assert!(output.contains("`src/auth/**`: Auth"));
    }

    fn minimal_brief_for_readme_tests() -> Brief {
        Brief {
            frontmatter: Frontmatter::default(),
            goal: "Fix the login bug".into(),
            identity: None,
            constraints: Constraints {
                hard: vec!["Do not break existing tests".into()],
                soft: vec![],
                ask_first: vec![],
            },
            sacred: vec![SacredEntry {
                path: "src/auth.rs".into(),
                reason: "Tenant resolution".into(),
                well_formed: true,
            }],
            assumptions: vec![],
            deliverable: None,
            unknown_sections: vec![],
        }
    }

    #[test]
    fn install_readme_creates_file_when_missing() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("README.md");
        let brief = crate::emit::readme::tests::minimal_brief_for_readme_tests();

        install_readme(&brief, &path).unwrap();

        let result = std::fs::read_to_string(&path).unwrap();
        assert!(result.starts_with("<brief:generated>"));
        assert!(result.contains("# Fix the login bug"));
        assert!(result.contains("Do not break existing tests **(REQUIRED)**"));
        assert!(result.contains("`src/auth.rs`: Tenant resolution"));
        assert!(result.trim_end().ends_with("</brief:generated>"));
    }

    #[test]
    fn install_readme_replaces_existing_marker_pair() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("README.md");
        std::fs::write(
            &path,
            "# My Project\n\nIntro.\n\n<brief:generated>\nstale brief content\n</brief:generated>\n\n## Other\n\nMore.\n",
        )
            .unwrap();
        let brief = crate::emit::readme::tests::minimal_brief_for_readme_tests();

        install_readme(&brief, &path).unwrap();

        let result = std::fs::read_to_string(&path).unwrap();
        assert!(result.contains("# My Project"));
        assert!(result.contains("Intro."));
        assert!(result.contains("## Other"));
        assert!(result.contains("More."));
        assert!(result.contains("# Fix the login bug"));
        assert!(!result.contains("stale brief content"));
        assert_eq!(result.matches("<brief:generated>").count(), 1);
        assert_eq!(result.matches("</brief:generated>").count(), 1);
    }

    #[test]
    fn install_readme_appends_when_no_markers() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("AGENTS.md");
        std::fs::write(&path, "# My Project\n\nFreeform agent notes.\n").unwrap();
        let brief = crate::emit::readme::tests::minimal_brief_for_readme_tests();

        install_agents_md(&brief, &path).unwrap();

        let result = std::fs::read_to_string(&path).unwrap();
        assert!(result.starts_with("# My Project"));
        assert!(result.contains("Freeform agent notes."));
        assert!(result.contains("<brief:generated>"));
        assert!(result.contains("# Fix the login bug"));
        assert!(result.trim_end().ends_with("</brief:generated>"));
    }

    #[test]
    fn install_readme_migrates_legacy_html_comment_markers() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("README.md");
        std::fs::write(
            &path,
            "# My Project\n\n<!-- brief:start -->\nold legacy\n<!-- brief:end -->\n\n## Other\n",
        )
            .unwrap();
        let brief = crate::emit::readme::tests::minimal_brief_for_readme_tests();

        install_agents_md(&brief, &path).unwrap();

        let result = std::fs::read_to_string(&path).unwrap();
        assert!(!result.contains("<!-- brief:start -->"));
        assert!(!result.contains("<!-- brief:end -->"));
        assert!(!result.contains("old legacy"));
        assert_eq!(result.matches("<brief:generated>").count(), 1);
        assert_eq!(result.matches("</brief:generated>").count(), 1);
        assert!(result.contains("# My Project"));
        assert!(result.contains("## Other"));
        assert!(result.contains("# Fix the login bug"));
    }


}